name: Lint and format
# https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py#requirements-file

on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Pub Dependencies
        run: flutter pub get

      - name: Verify Formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze
